In [2]:
#We need to install a package named gensim that will help us to download pretrained vectors from GloVe, Word2vec and fastText
#!pip install gensim

Collecting gensim

WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages)
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\dhruv\appdata\local\programs\python\python36\python.exe -m pip install --upgrade pip' command.

  Downloading gensim-4.1.2-cp36-cp36m-win_amd64.whl (24.0 MB)
Collecting smart-open>=1.8.1
  Downloading smart_open-5.2.1-py3-none-any.whl (58 kB)
Requirement already satisfied: scipy>=0.18.1 in c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages (from gensim) (1.5.1)
Collecting Cython==0.29.23
  Downloading Cython-0.29.23-cp36-cp36m-win_amd64.whl (1.6 MB)
Requirement already satisfied: dataclasses in c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages (from gensim) (0.8)
Requirement already satisfied: numpy>=1.17.0 in c:\users\dhruv\appdata\local\programs\python\python36\lib\site-packages (from gensim) (1.19.3)
Installing collected packages: smart-open, Cython, gensim
Successfully installed Cython-0.29.23 gensim-4.1.2 smart-open-5.2.1

In [1]:
#Importing neccesary libraries:
import numpy as np #To handle words in vector form
import gensim.downloader as api #Helps to download the word2Vec, glove pretrained models in notebook
from gensim.test.utils import datapath

In [2]:
#Now, we'll download the pretrained word vectors.
#In the hindi zip file, we're given 4 subfolders: 50, 100, 200, 300. They represent the dimensions of word vectors.
#We'll try all of them one by one.
#Let's try first 50 dimension one:
from gensim.models.word2vec import Word2Vec
model=Word2Vec.load('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/50/cbow/hi-d50-m2-cbow.model')

In [3]:
from multiprocessing import cpu_count 
#The multiprocessing package offers both local and remote concurrency, by using subprocesses instead of threads.
model

In [4]:
from gensim.models import KeyedVectors
# Store just the words + their trained embeddings.
word_vectors = model.wv 
word_vectors.save("word2vec.wordvectors")
# Load back with memory-mapping = read-only, shared across processes.
wv = KeyedVectors.load("word2vec.wordvectors", mmap='r')

In [5]:
vector1 = wv['फल']  # Get numpy vector of a word
#Note: It might not detect if we type hindi words in english font. So, we must type words in hindi font only mandatorily

In [6]:
vector1

memmap([-2.577101  ,  3.2237234 , -2.3370273 , -1.2639632 , -1.2701302 ,
         5.7682295 ,  1.1644784 ,  8.52332   ,  6.344735  ,  4.8631835 ,
         1.1041235 ,  1.5576736 ,  3.1735485 ,  0.91941327,  4.539088  ,
        -3.1069763 , -4.866369  ,  1.6900831 , -3.0524428 , -1.4413332 ,
        -4.344832  ,  3.6733735 ,  5.9467087 , -1.2673523 , -0.02576218,
         1.3488175 ,  4.3554773 , -2.198409  , -1.9031056 , -1.3953243 ,
         0.06250975,  1.6000719 , -0.27009594, -4.793821  , -7.235082  ,
        -8.743356  , -3.6901915 , -3.841936  ,  2.2221205 , -1.6071192 ,
         5.401825  ,  0.97118044, -1.4606669 , -2.214293  , -1.4989837 ,
        -3.651176  , -1.2440076 ,  1.6964933 ,  3.089168  , -3.9919286 ],
       dtype=float32)

In [7]:
vector2 = wv['केला']

In [8]:
vector2

memmap([-0.08102143,  2.274644  , -1.3528003 , -0.26310232,  0.5840593 ,
         3.6412673 ,  0.8273944 ,  1.5510343 ,  2.9310486 ,  1.6746405 ,
         0.9936286 , -1.0389575 ,  4.9545674 , -1.4346925 ,  1.5802468 ,
         1.3259856 , -1.5352265 , -0.6183625 , -1.312058  ,  4.3895464 ,
        -3.251289  ,  5.2165766 ,  0.5519009 , -0.13771765, -2.4140673 ,
        -1.8607434 ,  1.362285  , -1.3881952 , -2.445826  , -1.3627297 ,
         1.8221374 ,  0.9969925 , -3.3037164 ,  0.7928758 , -3.4332764 ,
        -2.281698  , -4.17308   ,  0.5565486 ,  3.2232685 , -0.48002782,
         2.047771  ,  1.6545259 , -0.6233354 ,  0.9687947 ,  2.3614235 ,
        -0.44626877,  0.40657243,  0.8215617 ,  1.7025241 ,  0.18743257],
       dtype=float32)

In [9]:
#Now, we'll try to build a cosine similarity function from scratch.
#It will help us to find wheather the given pair of words are similar or not.
#We'll try to manually experiment around with few similar and dissimilar words.
#Based on the results, we will set a specific threshold value.
#If the score is above threshold, then words are similar. If score is below threshold, then words are not similar.
num=np.dot(vector1,vector2)

In [10]:
from numpy.linalg import norm
den=norm(vector1)*norm(vector2)

In [11]:
den

387.44897

In [12]:
num

222.80933

In [13]:
cos=num/den

In [14]:
cos

0.5750675

In [15]:
#Since, the above words are very similar, we can keep a threshold value of 0.4.

In [16]:
#We tested it for a random value decided by us.
#But, we must apply it on the dataset given to us also.
#So, we'll define a function for cosine similarity.
#We'll call it directly then instead of performing so many steps for every entry.
import pandas as pd #To store the text file
df=pd.read_csv('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',lineterminator='\n',header=None)

In [17]:
df

             0          1    2
0      मोहब्बत      सेक्स  6.8
1          बाघ     बिल्ली  7.0
2        किताब      कागज़  7.6
3     कंप्यूटर    कीबोर्ड  7.6
4     कंप्यूटर    इंटरनेट  8.0
..         ...        ...  ...
60  मनोविज्ञान   चिकित्सक  7.0
61  मनोविज्ञान         मन  7.4
62  मनोविज्ञान  स्वास्थ्य  6.2
63  मनोविज्ञान    विज्ञान  7.0
64  मनोविज्ञान    अनुशासन  4.2

[65 rows x 3 columns]

In [18]:
df= df.rename(columns={0:'Word1',1:'Word2',2:'Ground Truth'}) #Renaming column names as per naming conventions

In [19]:
df

         Word1      Word2  Ground Truth
0      मोहब्बत      सेक्स           6.8
1          बाघ     बिल्ली           7.0
2        किताब      कागज़           7.6
3     कंप्यूटर    कीबोर्ड           7.6
4     कंप्यूटर    इंटरनेट           8.0
..         ...        ...           ...
60  मनोविज्ञान   चिकित्सक           7.0
61  मनोविज्ञान         मन           7.4
62  मनोविज्ञान  स्वास्थ्य           6.2
63  मनोविज्ञान    विज्ञान           7.0
64  मनोविज्ञान    अनुशासन           4.2

[65 rows x 3 columns]

In [20]:
df['Ground Truth']=df['Ground Truth'].apply(lambda x:x*.1) #Making ground truth values b/w 0 to 1

In [21]:
df

         Word1      Word2  Ground Truth
0      मोहब्बत      सेक्स          0.68
1          बाघ     बिल्ली          0.70
2        किताब      कागज़          0.76
3     कंप्यूटर    कीबोर्ड          0.76
4     कंप्यूटर    इंटरनेट          0.80
..         ...        ...           ...
60  मनोविज्ञान   चिकित्सक          0.70
61  मनोविज्ञान         मन          0.74
62  मनोविज्ञान  स्वास्थ्य          0.62
63  मनोविज्ञान    विज्ञान          0.70
64  मनोविज्ञान    अनुशासन          0.42

[65 rows x 3 columns]

In [22]:
wordsim=[item for item in df['Ground Truth']]

In [23]:
wordsim

[0.68,
 0.7000000000000001,
 0.76,
 0.76,
 0.8,
 0.6000000000000001,
 0.6200000000000001,
 0.76,
 0.6400000000000001,
 0.58,
 0.66,
 0.58,
 0.76,
 0.45999999999999996,
 0.7000000000000001,
 0.52,
 0.6200000000000001,
 0.76,
 0.8,
 0.7000000000000001,
 0.0,
 0.82,
 0.7000000000000001,
 0.78,
 0.1,
 0.78,
 0.9,
 0.6400000000000001,
 0.58,
 0.7400000000000001,
 0.78,
 0.66,
 0.66,
 0.8400000000000001,
 0.13999999999999999,
 0.04000000000000001,
 0.7000000000000001,
 0.7200000000000001,
 0.18000000000000002,
 0.68,
 0.8400000000000001,
 0.66,
 0.7400000000000001,
 0.13999999999999999,
 0.6200000000000001,
 0.020000000000000004,
 0.2,
 0.86,
 0.9199999999999999,
 0.8400000000000001,
 0.82,
 0.66,
 0.26,
 0.8,
 0.76,
 0.68,
 0.6200000000000001,
 0.52,
 0.7000000000000001,
 0.6400000000000001,
 0.7000000000000001,
 0.7400000000000001,
 0.6200000000000001,
 0.7000000000000001,
 0.42000000000000004]

In [24]:
#Defining function for cosine similarity:
def cos_sim(a,b):
    #Converting vectors to a numpy array:
    a=np.array(a)
    b=np.array(b)
    num=a.dot(b) #Numerator
    den=norm(a)*norm(b) #Denominator
    cos=num/den #Cosine similarity value
    return cos

# WORD2VEC-CBOW

In [25]:
#Now, we're given 5 threshold values(0.4, 0.5, 0.6, 0.7 and 0.8). If score is above threshold, then the words are similar.
#If the score is below threshold, then the words are dissimilar.
#So, we'll define a function for threshold that will help us to know the same.
def threshold(a,thresh):
    arr=[]
    for i in a: #Here a is the score
        if(i>=thresh):
            arr.append(1) #Words are similar
        else:
            arr.append(0) #Words are not similar
    return arr

In [26]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity\Word similarity\hindi.txt',encoding='utf-8')

In [27]:
wordsimilarity

In [28]:
Cbow=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        wordvec1=model.wv[word1] #As we used originally Word2vec CBOW only and saved it as model
        wordvec2=model.wv[word2]
        Cbow.append(cos_sim(wordvec1,wordvec2))

In [29]:
Cbow

[0.3129996,
 0.5336025,
 0.54693055,
 0.7682935,
 0.81086314,
 0.63731384,
 0.74887156,
 0.3745674,
 0.801967,
 0.4965293,
 0.8236989,
 0.8303863,
 0.7180418,
 0.4706635,
 0.44588384,
 0.22217478,
 0.6045512,
 0.28826952,
 0.43558094,
 0.55272144,
 -0.0051562167,
 0.6619058,
 -0.11893065,
 0.55090773,
 0.09757401,
 0.7276398,
 0.87685686,
 0.7947431,
 0.8422406,
 0.22198628,
 0.38418794,
 0.24394678,
 0.35865936,
 0.5928102,
 0.014033539,
 0.13512139,
 0.22652242,
 0.52978206,
 0.16959015,
 0.36144584,
 0.78953344,
 0.64052314,
 0.871589,
 0.34423447,
 0.37126175,
 0.20122457,
 0.22748998,
 0.2742843,
 0.66815543,
 0.46409026,
 0.43558094,
 0.41520742,
 0.15446109,
 0.21827163,
 0.7367997,
 0.6227161,
 0.16610095,
 -0.040998176,
 0.37255433,
 0.309465,
 0.45283476,
 0.2513045,
 0.4304416,
 0.7902854,
 0.58417773]

In [30]:
df['Similarity Score']=Cbow #We'll save the CBOW similarity score in new column

In [31]:
df

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.313000
1          बाघ     बिल्ली          0.70          0.533602
2        किताब      कागज़          0.76          0.546931
3     कंप्यूटर    कीबोर्ड          0.76          0.768293
4     कंप्यूटर    इंटरनेट          0.80          0.810863
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.452835
61  मनोविज्ञान         मन          0.74          0.251305
62  मनोविज्ञान  स्वास्थ्य          0.62          0.430442
63  मनोविज्ञान    विज्ञान          0.70          0.790285
64  मनोविज्ञान    अनुशासन          0.42          0.584178

[65 rows x 4 columns]

In [32]:
df1=df.copy()

In [33]:
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.313000
1          बाघ     बिल्ली          0.70          0.533602
2        किताब      कागज़          0.76          0.546931
3     कंप्यूटर    कीबोर्ड          0.76          0.768293
4     कंप्यूटर    इंटरनेट          0.80          0.810863
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.452835
61  मनोविज्ञान         मन          0.74          0.251305
62  मनोविज्ञान  स्वास्थ्य          0.62          0.430442
63  मनोविज्ञान    विज्ञान          0.70          0.790285
64  मनोविज्ञान    अनुशासन          0.42          0.584178

[65 rows x 4 columns]

In [34]:
#Now, we'll consider all 5 thresholds one by one and store their output as arrays
#Threshold is 0.4 and CBOW MODEL 50
cbow_sim =threshold(Cbow,0.4)

In [35]:
#To find accuracy, we must define the functions as follows:
def negate_vec(vect1):                                     # negation of binay array
    inverse_s = [2 if i==1 else i for i in vect1]
    inverse_s = [1 if i==0 else i for i in inverse_s]
    inverse_s = [0 if i==2 else i for i in inverse_s]
    return(inverse_s)
def accuracy(vec1,vec2):
    sim=[]
    vect1=negate_vec(vec1)
    sim = [a ^ b for a,b in zip(vect1,vec2)]
    num_ones = sim.count(1)
    return((num_ones/len(vect1))*100,sim)

In [36]:
wordsim_4=threshold(wordsim,0.4)
wordsim_5=threshold(wordsim,0.5)
wordsim_6=threshold(wordsim,0.6)
wordsim_7=threshold(wordsim,0.7)
wordsim_8=threshold(wordsim,0.8)

In [37]:
accuracy_4,sim_4 = accuracy(cbow_sim,wordsim_4)
df1['Label']=sim_4

In [38]:
#Reindexing according to convention asked
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"] 
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy:",accuracy_4," "," "," "] #Adding at last index

In [39]:
df1

         Word1      Word2 Similarity Score Ground Truth Label
0      मोहब्बत      सेक्स            0.313         0.68     0
1          बाघ     बिल्ली         0.533602          0.7     1
2        किताब      कागज़         0.546931         0.76     1
3     कंप्यूटर    कीबोर्ड         0.768293         0.76     1
4     कंप्यूटर    इंटरनेट         0.810863          0.8     1
..         ...        ...              ...          ...   ...
61  मनोविज्ञान         मन         0.251305         0.74     0
62  मनोविज्ञान  स्वास्थ्य         0.430442         0.62     1
63  मनोविज्ञान    विज्ञान         0.790285          0.7     1
64  मनोविज्ञान    अनुशासन         0.584178         0.42     1
65   Accuracy:    70.7692

[66 rows x 5 columns]

In [40]:
df1.to_csv("Q1_50_Cbow_similarity_4.csv") #Save file as csv

In [41]:
df1=df.copy() #To get initial values of dataframe again

In [42]:
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.313000
1          बाघ     बिल्ली          0.70          0.533602
2        किताब      कागज़          0.76          0.546931
3     कंप्यूटर    कीबोर्ड          0.76          0.768293
4     कंप्यूटर    इंटरनेट          0.80          0.810863
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.452835
61  मनोविज्ञान         मन          0.74          0.251305
62  मनोविज्ञान  स्वास्थ्य          0.62          0.430442
63  मनोविज्ञान    विज्ञान          0.70          0.790285
64  मनोविज्ञान    अनुशासन          0.42          0.584178

[65 rows x 4 columns]

In [43]:
#Now, we'll crepeat the same process for all models and thresholds to obtain 2*4*5=40 csv files
#Threshold is 0.5 and CBOW MODEL 50
cbow_sim =threshold(Cbow,0.5)
accuracy_5,sim_5 = accuracy(cbow_sim,wordsim_5)
df1['Label']=sim_5

In [44]:
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)

In [45]:
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]

In [46]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स            0.313         0.68     0
1            बाघ     बिल्ली         0.533602          0.7     1
2          किताब      कागज़         0.546931         0.76     1
3       कंप्यूटर    कीबोर्ड         0.768293         0.76     1
4       कंप्यूटर    इंटरनेट         0.810863          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.251305         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.430442         0.62     0
63    मनोविज्ञान    विज्ञान         0.790285          0.7     1
64    मनोविज्ञान    अनुशासन         0.584178         0.42     0
65  Accuracy is:    56.9231

[66 rows x 5 columns]

In [47]:
df1.to_csv("Q1_50_Cbow_similarity_5.csv")

In [48]:
df1=df.copy()

In [49]:
#Threshold is 0.6 and CBOW MODEL 50
cbow_sim =threshold(Cbow,0.6)
accuracy_6,sim_6 = accuracy(cbow_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]

In [50]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स            0.313         0.68     0
1            बाघ     बिल्ली         0.533602          0.7     0
2          किताब      कागज़         0.546931         0.76     0
3       कंप्यूटर    कीबोर्ड         0.768293         0.76     1
4       कंप्यूटर    इंटरनेट         0.810863          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.251305         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.430442         0.62     0
63    मनोविज्ञान    विज्ञान         0.790285          0.7     1
64    मनोविज्ञान    अनुशासन         0.584178         0.42     1
65  Accuracy is:    50.7692

[66 rows x 5 columns]

In [51]:
df1.to_csv("Q1_50_Cbow_similarity_6.csv")

In [52]:
#Threshold is 0.7 and CBOW MODEL 50
df1=df.copy()
cbow_sim =threshold(Cbow,0.7)
accuracy_7,sim_7 = accuracy(cbow_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]

In [53]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स            0.313         0.68     1
1            बाघ     बिल्ली         0.533602          0.7     0
2          किताब      कागज़         0.546931         0.76     0
3       कंप्यूटर    कीबोर्ड         0.768293         0.76     1
4       कंप्यूटर    इंटरनेट         0.810863          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.251305         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.430442         0.62     1
63    मनोविज्ञान    विज्ञान         0.790285          0.7     1
64    मनोविज्ञान    अनुशासन         0.584178         0.42     1
65  Accuracy is:    55.3846

[66 rows x 5 columns]

In [54]:
df1.to_csv("Q1_50_Cbow_similarity_7.csv")

In [55]:
#Threshold is 0.8 and CBOW MODEL 50
df1=df.copy()
cbow_sim =threshold(Cbow,0.8)
accuracy_8,sim_8 = accuracy(cbow_sim,wordsim_8)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]

In [56]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स            0.313         0.68     1
1            बाघ     बिल्ली         0.533602          0.7     1
2          किताब      कागज़         0.546931         0.76     1
3       कंप्यूटर    कीबोर्ड         0.768293         0.76     1
4       कंप्यूटर    इंटरनेट         0.810863          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.251305         0.74     1
62    मनोविज्ञान  स्वास्थ्य         0.430442         0.62     1
63    मनोविज्ञान    विज्ञान         0.790285          0.7     1
64    मनोविज्ञान    अनुशासन         0.584178         0.42     1
65  Accuracy is:    78.4615

[66 rows x 5 columns]

In [57]:
df1.to_csv("Q1_50_Cbow_similarity_8.csv")

In [58]:
#Now we'll deal with CBOW MODEL 100

In [59]:
cbow_model=Word2Vec.load('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/100/cbow/hi-d100-m2-cbow.model')

In [60]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity\Word similarity\hindi.txt',encoding='utf-8')

In [61]:
Cbow=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        wordvec1=cbow_model.wv[word1]
        wordvec2=cbow_model.wv[word2]
        Cbow.append(cos_sim(wordvec1,wordvec2))

In [62]:
df1=df.copy()

In [63]:
df1['Similarity Score']=Cbow

In [64]:
df=df1.copy()

In [65]:
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.290728
1          बाघ     बिल्ली          0.70          0.495231
2        किताब      कागज़          0.76          0.497515
3     कंप्यूटर    कीबोर्ड          0.76          0.710953
4     कंप्यूटर    इंटरनेट          0.80          0.757669
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.382300
61  मनोविज्ञान         मन          0.74          0.205375
62  मनोविज्ञान  स्वास्थ्य          0.62          0.379963
63  मनोविज्ञान    विज्ञान          0.70          0.757886
64  मनोविज्ञान    अनुशासन          0.42          0.458411

[65 rows x 4 columns]

In [66]:
#Threshold is 0.4 and CBOW MODEL 100
cbow_sim =threshold(Cbow,0.4)
accuracy_4,sim_4 = accuracy(cbow_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_100_Cbow_similarity_4.csv")

In [67]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.290728         0.68     0
1            बाघ     बिल्ली         0.495231          0.7     1
2          किताब      कागज़         0.497515         0.76     1
3       कंप्यूटर    कीबोर्ड         0.710953         0.76     1
4       कंप्यूटर    इंटरनेट         0.757669          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.205375         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.379963         0.62     0
63    मनोविज्ञान    विज्ञान         0.757886          0.7     1
64    मनोविज्ञान    अनुशासन         0.458411         0.42     1
65  Accuracy is:    61.5385

[66 rows x 5 columns]

In [68]:
#Threshold is 0.5 and CBOW MODEL 100
df1=df.copy()
cbow_sim =threshold(Cbow,0.5)
accuracy_5,sim_5 = accuracy(cbow_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_100_Cbow_similarity_5.csv")

In [69]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.290728         0.68     0
1            बाघ     बिल्ली         0.495231          0.7     0
2          किताब      कागज़         0.497515         0.76     0
3       कंप्यूटर    कीबोर्ड         0.710953         0.76     1
4       कंप्यूटर    इंटरनेट         0.757669          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.205375         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.379963         0.62     0
63    मनोविज्ञान    विज्ञान         0.757886          0.7     1
64    मनोविज्ञान    अनुशासन         0.458411         0.42     1
65  Accuracy is:    49.2308

[66 rows x 5 columns]

In [70]:
#Threshold is 0.6, CBOW MODEL 100
df1=df.copy()
cbow_sim =threshold(Cbow,0.6)
accuracy_6,sim_6 = accuracy(cbow_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_100_Cbow_similarity_6.csv")

In [71]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.290728         0.68     0
1            बाघ     बिल्ली         0.495231          0.7     0
2          किताब      कागज़         0.497515         0.76     0
3       कंप्यूटर    कीबोर्ड         0.710953         0.76     1
4       कंप्यूटर    इंटरनेट         0.757669          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.205375         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.379963         0.62     0
63    मनोविज्ञान    विज्ञान         0.757886          0.7     1
64    मनोविज्ञान    अनुशासन         0.458411         0.42     1
65  Accuracy is:    44.6154

[66 rows x 5 columns]

In [72]:
#Threshold is 0.7 and CBOW MODEL 100
df1=df.copy()
cbow_sim =threshold(Cbow,0.7)
accuracy_7,sim_7 = accuracy(cbow_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_100_Cbow_similarity_7.csv")

In [73]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.290728         0.68     1
1            बाघ     बिल्ली         0.495231          0.7     0
2          किताब      कागज़         0.497515         0.76     0
3       कंप्यूटर    कीबोर्ड         0.710953         0.76     1
4       कंप्यूटर    इंटरनेट         0.757669          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.205375         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.379963         0.62     1
63    मनोविज्ञान    विज्ञान         0.757886          0.7     1
64    मनोविज्ञान    अनुशासन         0.458411         0.42     1
65  Accuracy is:    52.3077

[66 rows x 5 columns]

In [74]:
#Threshold is 0.8 and CBOW MODEL 100
df1=df.copy()
cbow_sim =threshold(Cbow,0.8)
accuracy_8,sim_8 = accuracy(cbow_sim,wordsim_8)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_100_Cbow_similarity_8.csv")

In [75]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.290728         0.68     1
1            बाघ     बिल्ली         0.495231          0.7     1
2          किताब      कागज़         0.497515         0.76     1
3       कंप्यूटर    कीबोर्ड         0.710953         0.76     1
4       कंप्यूटर    इंटरनेट         0.757669          0.8     0
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.205375         0.74     1
62    मनोविज्ञान  स्वास्थ्य         0.379963         0.62     1
63    मनोविज्ञान    विज्ञान         0.757886          0.7     1
64    मनोविज्ञान    अनुशासन         0.458411         0.42     1
65  Accuracy is:    83.0769

[66 rows x 5 columns]

# WORD2VEC-FAST TEXT

In [76]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',encoding='utf-8')

In [77]:
from gensim.models import FastText
Ft=FastText.load('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/50/fasttext/hi-d50-m2-fasttext.model')

In [78]:
Ft_sim=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        vec1=Ft.wv[word1]
        vec2=Ft.wv[word2]
        Ft_sim.append(cos_sim(vec1,vec2))

In [79]:
df1=df.copy()

In [80]:
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.290728
1          बाघ     बिल्ली          0.70          0.495231
2        किताब      कागज़          0.76          0.497515
3     कंप्यूटर    कीबोर्ड          0.76          0.710953
4     कंप्यूटर    इंटरनेट          0.80          0.757669
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.382300
61  मनोविज्ञान         मन          0.74          0.205375
62  मनोविज्ञान  स्वास्थ्य          0.62          0.379963
63  मनोविज्ञान    विज्ञान          0.70          0.757886
64  मनोविज्ञान    अनुशासन          0.42          0.458411

[65 rows x 4 columns]

In [81]:
df1['Similarity Score']=Ft_sim
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.411275
1          बाघ     बिल्ली          0.70          0.697489
2        किताब      कागज़          0.76          0.598589
3     कंप्यूटर    कीबोर्ड          0.76          0.753008
4     कंप्यूटर    इंटरनेट          0.80          0.813158
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.624184
61  मनोविज्ञान         मन          0.74          0.444014
62  मनोविज्ञान  स्वास्थ्य          0.62          0.552433
63  मनोविज्ञान    विज्ञान          0.70          0.848998
64  मनोविज्ञान    अनुशासन          0.42          0.658615

[65 rows x 4 columns]

In [82]:
df=df1.copy()

In [83]:
#Threshold is 0.4 and FAST TEXT 50
df1=df.copy()
ft_sim =threshold(Ft_sim,0.4)
accuracy_4,sim_4 = accuracy(ft_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_50_FastText_similarity_4.csv")

In [84]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.411275         0.68     1
1            बाघ     बिल्ली         0.697489          0.7     1
2          किताब      कागज़         0.598589         0.76     1
3       कंप्यूटर    कीबोर्ड         0.753008         0.76     1
4       कंप्यूटर    इंटरनेट         0.813158          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.444014         0.74     1
62    मनोविज्ञान  स्वास्थ्य         0.552433         0.62     1
63    मनोविज्ञान    विज्ञान         0.848998          0.7     1
64    मनोविज्ञान    अनुशासन         0.658615         0.42     1
65  Accuracy is:    83.0769

[66 rows x 5 columns]

In [85]:
#Threshold is 0.5 and FAST TEXT 50
df1=df.copy()
ft_sim =threshold(Ft_sim,0.5)
accuracy_5,sim_5 = accuracy(ft_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_50_FastText_similarity_5.csv")

In [86]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.411275         0.68     0
1            बाघ     बिल्ली         0.697489          0.7     1
2          किताब      कागज़         0.598589         0.76     1
3       कंप्यूटर    कीबोर्ड         0.753008         0.76     1
4       कंप्यूटर    इंटरनेट         0.813158          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.444014         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.552433         0.62     1
63    मनोविज्ञान    विज्ञान         0.848998          0.7     1
64    मनोविज्ञान    अनुशासन         0.658615         0.42     0
65  Accuracy is:    83.0769

[66 rows x 5 columns]

In [87]:
#Threshold is 0.6 and FAST TEXT 50
df1=df.copy()
ft_sim =threshold(Ft_sim,0.6)
accuracy_6,sim_6 = accuracy(ft_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_50_FastText_similarity_6.csv")

In [88]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.411275         0.68     0
1            बाघ     बिल्ली         0.697489          0.7     1
2          किताब      कागज़         0.598589         0.76     0
3       कंप्यूटर    कीबोर्ड         0.753008         0.76     1
4       कंप्यूटर    इंटरनेट         0.813158          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.444014         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.552433         0.62     0
63    मनोविज्ञान    विज्ञान         0.848998          0.7     1
64    मनोविज्ञान    अनुशासन         0.658615         0.42     0
65  Accuracy is:    56.9231

[66 rows x 5 columns]

In [89]:
#Threshold is 0.7 and FAST TEXT 50
df1=df.copy()
ft_sim =threshold(Ft_sim,0.7)
accuracy_7,sim_7 = accuracy(ft_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_50_FastText_similarity_7.csv")

In [90]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.411275         0.68     1
1            बाघ     बिल्ली         0.697489          0.7     0
2          किताब      कागज़         0.598589         0.76     0
3       कंप्यूटर    कीबोर्ड         0.753008         0.76     1
4       कंप्यूटर    इंटरनेट         0.813158          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.444014         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.552433         0.62     1
63    मनोविज्ञान    विज्ञान         0.848998          0.7     1
64    मनोविज्ञान    अनुशासन         0.658615         0.42     1
65  Accuracy is:    55.3846

[66 rows x 5 columns]

In [91]:
#Threshold is 0.8 and FAST TEXT 50
df1=df.copy()
ft_sim =threshold(Ft_sim,0.8)
accuracy_8,sim_8 = accuracy(ft_sim,wordsim_8)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_50_FastText_similarity_8.csv")

In [92]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.411275         0.68     1
1            बाघ     बिल्ली         0.697489          0.7     1
2          किताब      कागज़         0.598589         0.76     1
3       कंप्यूटर    कीबोर्ड         0.753008         0.76     1
4       कंप्यूटर    इंटरनेट         0.813158          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.444014         0.74     1
62    मनोविज्ञान  स्वास्थ्य         0.552433         0.62     1
63    मनोविज्ञान    विज्ञान         0.848998          0.7     0
64    मनोविज्ञान    अनुशासन         0.658615         0.42     1
65  Accuracy is:    78.4615

[66 rows x 5 columns]

In [93]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',encoding='utf-8')

Ft=FastText.load('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/100/fasttext/hi-d100-m2-fasttext.model')

In [94]:
Ft_sim=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        vec1=Ft.wv[word1]
        vec2=Ft.wv[word2]
        Ft_sim.append(cos_sim(vec1,vec2))

In [95]:
df1=df.copy()

In [96]:
df1['Similarity Score']=Ft_sim
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.337140
1          बाघ     बिल्ली          0.70          0.647487
2        किताब      कागज़          0.76          0.533919
3     कंप्यूटर    कीबोर्ड          0.76          0.690811
4     कंप्यूटर    इंटरनेट          0.80          0.711636
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.523750
61  मनोविज्ञान         मन          0.74          0.390577
62  मनोविज्ञान  स्वास्थ्य          0.62          0.523397
63  मनोविज्ञान    विज्ञान          0.70          0.807686
64  मनोविज्ञान    अनुशासन          0.42          0.524375

[65 rows x 4 columns]

In [97]:
df=df1.copy()

In [98]:
#Threshold is 0.4 and FAST TEXT 100
df1=df.copy()
ft_sim =threshold(Ft_sim,0.4)
accuracy_4,sim_4 = accuracy(ft_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_100_FastText_similarity_4.csv")

In [99]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स          0.33714         0.68     0
1            बाघ     बिल्ली         0.647487          0.7     1
2          किताब      कागज़         0.533919         0.76     1
3       कंप्यूटर    कीबोर्ड         0.690811         0.76     1
4       कंप्यूटर    इंटरनेट         0.711636          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.390577         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.523397         0.62     1
63    मनोविज्ञान    विज्ञान         0.807686          0.7     1
64    मनोविज्ञान    अनुशासन         0.524375         0.42     1
65  Accuracy is:    89.2308

[66 rows x 5 columns]

In [100]:
#Threshold is 0.5 and FAST TEXT 100
df1=df.copy()
ft_sim =threshold(Ft_sim,0.5)
accuracy_5,sim_5 = accuracy(ft_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_100_FastText_similarity_5.csv")

In [101]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स          0.33714         0.68     0
1            बाघ     बिल्ली         0.647487          0.7     1
2          किताब      कागज़         0.533919         0.76     1
3       कंप्यूटर    कीबोर्ड         0.690811         0.76     1
4       कंप्यूटर    इंटरनेट         0.711636          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.390577         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.523397         0.62     1
63    मनोविज्ञान    विज्ञान         0.807686          0.7     1
64    मनोविज्ञान    अनुशासन         0.524375         0.42     0
65  Accuracy is:    66.1538

[66 rows x 5 columns]

In [102]:
#Threshold is 0.6 and FAST TEXT 100
df1=df.copy()
ft_sim =threshold(Ft_sim,0.6)
accuracy_6,sim_6 = accuracy(ft_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_100_FastText_similarity_6.csv")

In [103]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स          0.33714         0.68     0
1            बाघ     बिल्ली         0.647487          0.7     1
2          किताब      कागज़         0.533919         0.76     0
3       कंप्यूटर    कीबोर्ड         0.690811         0.76     1
4       कंप्यूटर    इंटरनेट         0.711636          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.390577         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.523397         0.62     0
63    मनोविज्ञान    विज्ञान         0.807686          0.7     1
64    मनोविज्ञान    अनुशासन         0.524375         0.42     1
65  Accuracy is:    47.6923

[66 rows x 5 columns]

In [104]:
#Threshold is 0.7 and FAST TEXT 100
df1=df.copy()
ft_sim =threshold(Ft_sim,0.7)
accuracy_7,sim_7 = accuracy(ft_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_100_FastText_similarity_7.csv")

In [105]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स          0.33714         0.68     1
1            बाघ     बिल्ली         0.647487          0.7     0
2          किताब      कागज़         0.533919         0.76     0
3       कंप्यूटर    कीबोर्ड         0.690811         0.76     0
4       कंप्यूटर    इंटरनेट         0.711636          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.390577         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.523397         0.62     1
63    मनोविज्ञान    विज्ञान         0.807686          0.7     1
64    मनोविज्ञान    अनुशासन         0.524375         0.42     1
65  Accuracy is:    53.8462

[66 rows x 5 columns]

In [106]:
#Threshold is 0.8 and FAST TEXT 100
df1=df.copy()
ft_sim =threshold(Ft_sim,0.8)
accuracy_8,sim_8 = accuracy(ft_sim,wordsim_8)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_100_FastText_similarity_8.csv")

In [107]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स          0.33714         0.68     1
1            बाघ     बिल्ली         0.647487          0.7     1
2          किताब      कागज़         0.533919         0.76     1
3       कंप्यूटर    कीबोर्ड         0.690811         0.76     1
4       कंप्यूटर    इंटरनेट         0.711636          0.8     0
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.390577         0.74     1
62    मनोविज्ञान  स्वास्थ्य         0.523397         0.62     1
63    मनोविज्ञान    विज्ञान         0.807686          0.7     0
64    मनोविज्ञान    अनुशासन         0.524375         0.42     1
65  Accuracy is:         80

[66 rows x 5 columns]

# Glove

In [108]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',encoding='utf-8')

file = open("D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/50/glove/hi-d50-glove.txt",encoding='utf-8',errors='ignore')
cntrl=1
vocab=[]
glove={}
for line in file:
    line=line.strip('\n')
    line=line.split(" ") # separating the data wiht the \n
    wv=line.pop(0)
    line= [float(i) for i in line]
    glove[wv]=line
    cntrl=cntrl+1

In [109]:
glove_sim=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        vec1=glove[word1]
        vec2=glove[word2]
        glove_sim.append(cos_sim(vec1,vec2))

In [110]:
df1=df.copy()

In [111]:
df1['Similarity Score']=glove_sim
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.433053
1          बाघ     बिल्ली          0.70          0.599653
2        किताब      कागज़          0.76          0.640784
3     कंप्यूटर    कीबोर्ड          0.76          0.632179
4     कंप्यूटर    इंटरनेट          0.80          0.798327
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.601080
61  मनोविज्ञान         मन          0.74          0.380867
62  मनोविज्ञान  स्वास्थ्य          0.62          0.597148
63  मनोविज्ञान    विज्ञान          0.70          0.830485
64  मनोविज्ञान    अनुशासन          0.42          0.614322

[65 rows x 4 columns]

In [112]:
df=df1.copy()

In [113]:
#Threshold is 0.4 and FAST TEXT 50
df1=df.copy()
glove_sim =threshold(glove_sim,0.4)
accuracy_4,sim_4 = accuracy(glove_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_50_Glove_similarity_4.csv")

In [114]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.433053         0.68     1
1            बाघ     बिल्ली         0.599653          0.7     1
2          किताब      कागज़         0.640784         0.76     1
3       कंप्यूटर    कीबोर्ड         0.632179         0.76     1
4       कंप्यूटर    इंटरनेट         0.798327          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.380867         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.597148         0.62     1
63    मनोविज्ञान    विज्ञान         0.830485          0.7     1
64    मनोविज्ञान    अनुशासन         0.614322         0.42     1
65  Accuracy is:    84.6154

[66 rows x 5 columns]

In [115]:
#Threshold is 0.5 and GLOVE 50
df1=df.copy()
glove_sim =threshold(glove_sim,0.5)
accuracy_5,sim_5 = accuracy(glove_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_50_Glove_similarity_5.csv")

In [116]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.433053         0.68     1
1            बाघ     बिल्ली         0.599653          0.7     1
2          किताब      कागज़         0.640784         0.76     1
3       कंप्यूटर    कीबोर्ड         0.632179         0.76     1
4       कंप्यूटर    इंटरनेट         0.798327          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.380867         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.597148         0.62     1
63    मनोविज्ञान    विज्ञान         0.830485          0.7     1
64    मनोविज्ञान    अनुशासन         0.614322         0.42     0
65  Accuracy is:    81.5385

[66 rows x 5 columns]

In [117]:
#Threshold is 0.6 and GLOVE 50
df1=df.copy()
glove_sim =threshold(glove_sim,0.6)
accuracy_6,sim_6 = accuracy(glove_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_50_Glove_similarity_6.csv")

In [118]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.433053         0.68     1
1            बाघ     बिल्ली         0.599653          0.7     1
2          किताब      कागज़         0.640784         0.76     1
3       कंप्यूटर    कीबोर्ड         0.632179         0.76     1
4       कंप्यूटर    इंटरनेट         0.798327          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.380867         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.597148         0.62     1
63    मनोविज्ञान    विज्ञान         0.830485          0.7     1
64    मनोविज्ञान    अनुशासन         0.614322         0.42     0
65  Accuracy is:    76.9231

[66 rows x 5 columns]

In [119]:
#Threshold is 0.7 and GLOVE 50
df1=df.copy()
glove_sim =threshold(glove_sim,0.7)
accuracy_7,sim_7 = accuracy(glove_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_50_Glove_similarity_7.csv")

In [120]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.433053         0.68     0
1            बाघ     बिल्ली         0.599653          0.7     1
2          किताब      कागज़         0.640784         0.76     1
3       कंप्यूटर    कीबोर्ड         0.632179         0.76     1
4       कंप्यूटर    इंटरनेट         0.798327          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.380867         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.597148         0.62     0
63    मनोविज्ञान    विज्ञान         0.830485          0.7     1
64    मनोविज्ञान    अनुशासन         0.614322         0.42     0
65  Accuracy is:    56.9231

[66 rows x 5 columns]

In [121]:
#Threshold is 0.8 and GLOVE 50
df1=df.copy()
glove_sim =threshold(glove_sim,0.8)
accuracy_8,sim_8 = accuracy(glove_sim,wordsim_7)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_50_Glove_similarity_8.csv")

In [122]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.433053         0.68     0
1            बाघ     बिल्ली         0.599653          0.7     1
2          किताब      कागज़         0.640784         0.76     1
3       कंप्यूटर    कीबोर्ड         0.632179         0.76     1
4       कंप्यूटर    इंटरनेट         0.798327          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.380867         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.597148         0.62     0
63    मनोविज्ञान    विज्ञान         0.830485          0.7     1
64    मनोविज्ञान    अनुशासन         0.614322         0.42     0
65  Accuracy is:    56.9231

[66 rows x 5 columns]

In [123]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',encoding='utf-8')

file = open("D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/100/glove/hi-d100-glove.txt",encoding='utf-8',errors='ignore')
cntrl=1
vocab=[]
glove={}
for line in file:
    line=line.strip('\n')
    line=line.split(" ") # separating the data wiht the \n
    wv=line.pop(0)
    line= [float(i) for i in line]
    glove[wv]=line
    cntrl=cntrl+1

In [124]:
glove_sim=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        vec1=glove[word1]
        vec2=glove[word2]
        glove_sim.append(cos_sim(vec1,vec2))

In [125]:
df1=df.copy()

In [126]:
df1['Similarity Score']=glove_sim
df1

         Word1      Word2  Ground Truth  Similarity Score
0      मोहब्बत      सेक्स          0.68          0.348015
1          बाघ     बिल्ली          0.70          0.545649
2        किताब      कागज़          0.76          0.577248
3     कंप्यूटर    कीबोर्ड          0.76          0.555780
4     कंप्यूटर    इंटरनेट          0.80          0.698266
..         ...        ...           ...               ...
60  मनोविज्ञान   चिकित्सक          0.70          0.488069
61  मनोविज्ञान         मन          0.74          0.365904
62  मनोविज्ञान  स्वास्थ्य          0.62          0.515601
63  मनोविज्ञान    विज्ञान          0.70          0.745068
64  मनोविज्ञान    अनुशासन          0.42          0.504125

[65 rows x 4 columns]

In [127]:
df=df1.copy()

In [128]:
#Threshold is 0.4 and FAST TEXT 50
df1=df.copy()
glove_sim =threshold(glove_sim,0.4)
accuracy_4,sim_4 = accuracy(glove_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_50_Glove_similarity_4.csv")

In [129]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.348015         0.68     0
1            बाघ     बिल्ली         0.545649          0.7     1
2          किताब      कागज़         0.577248         0.76     1
3       कंप्यूटर    कीबोर्ड          0.55578         0.76     1
4       कंप्यूटर    इंटरनेट         0.698266          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.365904         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.515601         0.62     1
63    मनोविज्ञान    विज्ञान         0.745068          0.7     1
64    मनोविज्ञान    अनुशासन         0.504125         0.42     1
65  Accuracy is:         80

[66 rows x 5 columns]

In [130]:
#Threshold is 0.5 and GLOVE 100
df1=df.copy()
glove_sim =threshold(glove_sim,0.5)
accuracy_5,sim_5 = accuracy(glove_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_100_Glove_similarity_5.csv")

In [131]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.348015         0.68     0
1            बाघ     बिल्ली         0.545649          0.7     1
2          किताब      कागज़         0.577248         0.76     1
3       कंप्यूटर    कीबोर्ड          0.55578         0.76     1
4       कंप्यूटर    इंटरनेट         0.698266          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.365904         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.515601         0.62     1
63    मनोविज्ञान    विज्ञान         0.745068          0.7     1
64    मनोविज्ञान    अनुशासन         0.504125         0.42     0
65  Accuracy is:    76.9231

[66 rows x 5 columns]

In [132]:
#Threshold is 0.6 and GLOVE 100
df1=df.copy()
glove_sim =threshold(glove_sim,0.6)
accuracy_6,sim_6 = accuracy(glove_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_100_Glove_similarity_6.csv")

In [133]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.348015         0.68     0
1            बाघ     बिल्ली         0.545649          0.7     1
2          किताब      कागज़         0.577248         0.76     1
3       कंप्यूटर    कीबोर्ड          0.55578         0.76     1
4       कंप्यूटर    इंटरनेट         0.698266          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.365904         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.515601         0.62     1
63    मनोविज्ञान    विज्ञान         0.745068          0.7     1
64    मनोविज्ञान    अनुशासन         0.504125         0.42     0
65  Accuracy is:    75.3846

[66 rows x 5 columns]

In [134]:
#Threshold is 0.7 and GLOVE 100
df1=df.copy()
glove_sim =threshold(glove_sim,0.7)
accuracy_7,sim_7 = accuracy(glove_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_100_Glove_similarity_7.csv")

In [135]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.348015         0.68     1
1            बाघ     बिल्ली         0.545649          0.7     1
2          किताब      कागज़         0.577248         0.76     1
3       कंप्यूटर    कीबोर्ड          0.55578         0.76     1
4       कंप्यूटर    इंटरनेट         0.698266          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.365904         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.515601         0.62     0
63    मनोविज्ञान    विज्ञान         0.745068          0.7     1
64    मनोविज्ञान    अनुशासन         0.504125         0.42     0
65  Accuracy is:    67.6923

[66 rows x 5 columns]

In [136]:
#Threshold is 0.8 and GLOVE 100
df1=df.copy()
glove_sim =threshold(glove_sim,0.8)
accuracy_8,sim_8 = accuracy(glove_sim,wordsim_7)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_100_Glove_similarity_8.csv")

In [137]:
df1

           Word1      Word2 Similarity Score Ground Truth Label
0        मोहब्बत      सेक्स         0.348015         0.68     1
1            बाघ     बिल्ली         0.545649          0.7     1
2          किताब      कागज़         0.577248         0.76     1
3       कंप्यूटर    कीबोर्ड          0.55578         0.76     1
4       कंप्यूटर    इंटरनेट         0.698266          0.8     1
..           ...        ...              ...          ...   ...
61    मनोविज्ञान         मन         0.365904         0.74     0
62    मनोविज्ञान  स्वास्थ्य         0.515601         0.62     0
63    मनोविज्ञान    विज्ञान         0.745068          0.7     1
64    मनोविज्ञान    अनुशासन         0.504125         0.42     0
65  Accuracy is:    67.6923

[66 rows x 5 columns]

# SKIPGRAM

In [ ]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',encoding='utf-8')

sg = Word2Vec.load("D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/50/sg/hi-d50-m2-sg.model")

In [ ]:
Sg=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        vec1=sg.wv[word1]
        vec2=sg.wv[word2]
        Sg.append(cos_sim(vec1,vec2))

In [ ]:
df1=df.copy()

In [ ]:
df1['Similarity Score']=Sg
df1

In [ ]:
df=df1.copy()

In [ ]:
#Threshold is 0.4 and SKIPGRAM 50
df1=df.copy()
Sg_sim =threshold(Sg,0.4)
accuracy_4,sim_4 = accuracy(Sg_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_50_SkipGram_similarity_4.csv")

In [ ]:
#Threshold is 0.5 and SKIPGRAM 50
df1=df.copy()
Sg_sim =threshold(Sg,0.5)
accuracy_5,sim_5 = accuracy(Sg_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_50_SkipGram_similarity_5.csv")

In [ ]:
#Threshold is 0.6 and SKIPGRAM 50
df1=df.copy()
Sg_sim =threshold(Sg,0.6)
accuracy_6,sim_6 = accuracy(Sg_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_50_SkipGram_similarity_5.csv")

In [ ]:
#Threshold is 0.7 and SKIPGRAM 50
df1=df.copy()
Sg_sim =threshold(Sg,0.7)
accuracy_7,sim_7 = accuracy(Sg_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_50_SkipGram_similarity_7.csv")

In [ ]:
#Threshold is 0.8 and SKIPGRAM 50
df1=df.copy()
Sg_sim =threshold(Sg,0.8)
accuracy_8,sim_8 = accuracy(Sg_sim,wordsim_8)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_50_SkipGram_similarity_8.csv")

In [ ]:
wordsimilarity=open('D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/Word similarity/Word similarity/hindi.txt',encoding='utf-8')

sg = Word2Vec.load("D:/001M-Tech IIT-Kanpur/1Subjects/INFO RETRIEVAL/A-2/hi/hi/100/sg/hi-d100-m2-sg.model")

In [ ]:
Sg=[]
for line in wordsimilarity:
    line=line.strip("\n").split(",")
    if len(line)>1:
        word1=line[0].strip(" ")
        word2=line[1].strip(" ")
        vec1=sg.wv[word1]
        vec2=sg.wv[word2]
        Sg.append(cos_sim(vec1,vec2))

In [ ]:
df1=df.copy()

In [ ]:
df1['Similarity Score']=Sg
df1

In [ ]:
df=df1.copy()

In [ ]:
#Threshold is 0.4 and SKIPGRAM 100
df1=df.copy()
Sg_sim =threshold(Sg,0.4)
accuracy_4,sim_4 = accuracy(Sg_sim,wordsim_4)
df1['Label']=sim_4
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_4," "," "," "]
df1.to_csv("Q1_100_SkipGram_similarity_4.csv")

In [ ]:
#Threshold is 0.5 and SKIPGRAM 100
df1=df.copy()
Sg_sim =threshold(Sg,0.5)
accuracy_5,sim_5 = accuracy(Sg_sim,wordsim_5)
df1['Label']=sim_5
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_5," "," "," "]
df1.to_csv("Q1_100_SkipGram_similarity_5.csv")

In [ ]:
#Threshold is 0.6 and SKIPGRAM 100
df1=df.copy()
Sg_sim =threshold(Sg,0.6)
accuracy_6,sim_6 = accuracy(Sg_sim,wordsim_6)
df1['Label']=sim_6
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_6," "," "," "]
df1.to_csv("Q1_100_SkipGram_similarity_6.csv")

In [ ]:
#Threshold is 0.7 and SKIPGRAM 100
df1=df.copy()
Sg_sim =threshold(Sg,0.7)
accuracy_7,sim_7 = accuracy(Sg_sim,wordsim_7)
df1['Label']=sim_7
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_7," "," "," "]
df1.to_csv("Q1_100_SkipGram_similarity_7.csv")

In [ ]:
#Threshold is 0.8 and SKIPGRAM 100
df1=df.copy()
Sg_sim =threshold(Sg,0.8)
accuracy_8,sim_8 = accuracy(Sg_sim,wordsim_8)
df1['Label']=sim_8
column_title=["Word1","Word2", "Similarity Score","Ground Truth","Label"]
df1=df1.reindex(columns=column_title)
df1.loc[65]=["Accuracy is:",accuracy_8," "," "," "]
df1.to_csv("Q1_100_SkipGram_similarity_8.csv")